### ISSUE TITLE
Compile for NDK20 down needs fix

### ISSUE THREAD

**Issue by ghost** [MAJigsaw77/hxlua#2]
ik you not gonna do smth but im trying my luck here and r15c compiles are fixed i can build it

Screenshot of error:
![Screenshot_2023_0509_215455](https://github.com/MAJigsaw77/hxlua/assets/82843871/189efe91-7c77-4def-b99e-b05b2b10a361)

**Comment by MAJigsaw77** [comment]
That's not bindings issue, it's lua's internal issue

**Comment by MAJigsaw77** [comment]
You can raport issues about lua [here](https://www.lua.org/lua-l.html) tough

**Comment by MAJigsaw77** [comment]
I recommend you to use NDK r21e on android

**Comment by ghost** [comment]
> That's not bindings issue, it's lua's internal issue

well shit

**Comment by ghost** [comment]
and i mean cant u try fix in ur source? you didnt use submodule if u know how to fix u can ig idfk

**Comment by MAJigsaw77** [comment]
> and i mean cant u try fix in ur source? you didnt use submodule if u know how to fix u can ig idfk

I'm just using thier sdk, I won't modify it for their issues, just raport the issue on thier website or use a newer ndk
