### ISSUE TITLE
Problem compiling with hxlua

### ISSUE THREAD

**Issue by Heropowerbrine** [MAJigsaw77/hxlua#4]
I was using hxlua to replace linc luajit for a port when this happened
![Screenshot 2023-06-08 13 38 04](https://github.com/MAJigsaw77/hxlua/assets/78842166/967721e1-1d68-442e-a54a-04cad4e23f6c)
![Screenshot 2023-06-08 13 38 13](https://github.com/MAJigsaw77/hxlua/assets/78842166/59b7cf53-c73a-4e32-889b-0d63e1fdc877)

**Comment by MAJigsaw77** [comment]
Try to remove the export folder and compile again, I haven't encountered a error like this before
