### ISSUE TITLE
Cannot build with lime

### ISSUE THREAD

**Issue by 47rooks** [MAJigsaw77/hxlua#6]
Trying to build a lime project with hxlua I get this error:

```
LuaTest> lime build windows
Error: Could not find haxelib "hxlua", does it need to be installed?
```

I am using a local haxelib in the project and it is installed:

```
LuaTest> haxelib list
flixel: [5.8.0]
hxcpp-debug-server: [1.2.4]
hxcpp: [4.3.2]
hxlua: [1.6.2]
lime: [8.2.1]
openfl: [9.4.0]
```

**Comment by moxie-coder** [comment]
`haxelib —global install hxlua`

**Comment by 47rooks** [comment]
This works but I'm puzzled. It has to be installed both in the local repo and the global one ? Why is that ?

**Comment by moxie-coder** [comment]
> This works but I'm puzzled. It has to be installed both in the local repo and the global one ? Why is that ?

if I had to guess, I’d say the build.xml is looking for the haxelib from the global cache, not the one from a local repository, since it’s looking for `haxelib:hxlua`, and I’m guessing that’s only looking in the global haxelibs, not local ones

**Comment by 47rooks** [comment]
ok - that was my guess too - question for the externs/tools people on the discord I guess. Thanx thoug. This gets me going again

Thx
D

**Comment by moxie-coder** [comment]
> ok - that was my guess too - question for the externs/tools people on the discord I guess. Thanx thoug. This gets me going again
> 
> Thx D

it’s more of an hxcpp thing, since it’s usually compiled to C++ code on desktop platforms
